### ISSUE TITLE
RFC: how to correctly add new pam module using authselect?

### ISSUE THREAD

**Issue by alfonz19** [pbrezina/authselect#185] opened 2019-11-05 16:24 UTC
I got my own yubikey, which documentation explains: add line "auth       required   pam_u2f.so" to correct pam file on correct line. Excellent documentation indeed. Ok, so I managed to find 'correct' files and 'correct' lines, hopefully, only to discover fedoras authselect,  and this post 

https://alan.ivey.dev/posts/2019/yubikey-login-to-fedora-with-u2f-via-authselect/

documenting how to create profile for yubikey using authselect. But it's rather cryptic not explaining how it works, and where is pam_u2f.so coming from. I (think I)managed to learn and understand whole pam architecture, but I totally do not grasp authselect. Is there any documentation of this, which explains how to customize pam modules / how to add somehow somewhere extra required/optional pam module? I cannot see any way from authselect to newly added pam_u2f.so somewhere.

So for example to allow passwordless login one need to add "auth       sufficient   pam_u2f.so cue" to /etc/pam.d/sudo before like "auth       include      system-auth". Which is (probably) valid for arch or debian, but not according to authselect. What would be correct way here?

Thanks.

**Comment by pbrezina** [comment] 2019-11-06 08:50
Hi, you can use `authselect enable-feature with-pam-u2f` (or `with-pam-u2f-2fa`) with authselect 1.1 which will create pam configuration that you desire.

**Comment by pbrezina** [comment] 2019-11-06 08:50
See: https://github.com/pbrezina/authselect/blob/master/profiles/sssd/README#L61

**Comment by martin-mucha** [comment] 2019-11-07 14:27
Thanks! I will check it shortly. Please do not close yet, I need to check it when I'm back at fedora-box, and I don't want to create new tickets if I just need to ask something small. ~ What I'm not sure how it will work, is parameterizing u2f.pam and/or maybe influencing whole pam flow when u2f is in play. But maybe it will be clear, when I check it again with your info.

What I'm currently after, well if you care, is that u2f does not have any pin support. Thus if you forget you key plugged in otherwise low-risk env, anyone can get access trivially. But one can stack modules to simulate that pin after button is pressed on yubikey. And going even further, the pin might be required only if you're unlocking/logging screen. If you are doing privileged operations while logged in, the pin is obviously just a nuisance, so for sudo for example when you are logged in, the pin isn't needed. Well I'm just talking from the top of my head, I did not thought about all implications yet.

**Comment by pbrezina** [comment] 2019-11-07 14:38
What is it that you want to achieve? pam_u2f is a simple module to help you to authenticate with yubikey (and other compatible devices). You can setup a 2fa with it which makes you authenticate with password+yubikey combo. Perhaps you are looking for a more advance use case and you should look into FreeIPA smartcards/2fa capabilities.

**Comment by alfonz19** [comment] 2019-11-23 20:13
Sorry for the delay, I got back to it only now.
I experimented with the authselect, and while I understand pam subsystem more or less, I totally do not understand authselect.

My system:
```
cat /etc/redhat-release 
Fedora release 30 (Thirty)
```
and it's an cinnamon spin.

authselect version (no -version flag?)
```
dnf provides /usr/bin/authselect
authselect-1.0.3-1.fc30.x86_64 : Configures authentication
     ...: and identity sources from supported profiles
Repo        : fedora
Matched from:
Filename    : /usr/bin/authselect

authselect-1.1-1.fc30.x86_64 : Configures authentication and
     ...: identity sources from supported profiles
Repo        : @System
Matched from:
Filename    : /usr/bin/authselect

authselect-1.1-1.fc30.x86_64 : Configures authentication and
     ...: identity sources from supported profiles
Repo        : updates
Matched from:
Filename    : /usr/bin/authselect
```

ok, so to begin with, it kept complaining about `/etc/nssswitch.conf` not being generated by authselect, but it's rather sure, that noone ever touch that file. I found some bugreports about that, so I proceed with:

```
authselect select sssd --force
authselect enable-feature with-silent-lastlog
authselect enable-feature with-pam-u2f
```

for some reason this produced twice `nemo` application to crash (while it wasn't running), and one system-core crash. So question 1: why is that possible to happen? Aren't we just modifying pam.d files?

question 2: so now I have sssd profile as `current`. Where is this sssd profile has it's files, so that I can check them? I can see some files in `/etc/authselect` but there is no profile information...

question 3: lets say, that I checked those files from question 2, and for now lets work with file `/etc/authselect/system-auth`. Configuration there for pam_u2f is:

```
auth        sufficient                                   pam_u2f.so cue
```

which happens to be what I'd like. But lets say, that I want to customize it (there's log of options for this pam) and some login managers (according to what I read) might have problems with option `cue`. So lets say I'd like to edit this for this `sssd` profile, not to use option `cue`. Where is the proper place to do such modification, how to say, that "with-pam-u2f" will not produce `cue` option?

question 4: so in attempt to find the source files, I created new profile like `authselect show howDoesThisWork`, but sadly to find custom profiles in special location. OK, but all these generated files are completely empty (np with that), which makes authselect commands to fail (not actually that ok). Alright, so is there somewhere some documentation, how to correctly setup these files from authselect perspective (I know pam.d specifics). And last step: to remove this custom profile `howDoesThisWork` is it ok to just delete it (as there is no command for that) or should we do something special?

anyways `enable-feature with-pam-u2f` seems to be working, well at least for screensaver and sudo, so thanks for helping me with that! Have a nice evening (if you are reading just now); I have to logout now, to verify login functionality ;)

**Comment by pbrezina** [comment] 2019-11-28 11:10
> ```
> cat /etc/redhat-release 
> Fedora release 30 (Thirty)
> ```
> 
> and it's an cinnamon spin.
> 
> authselect version (no -version flag?)
> dnf provides /usr/bin/authselect
> authselect-1.0.3-1.fc30.x86_64 : Configures authentication
> authselect-1.1-1.fc30.x86_64 : Configures authentication and
> authselect-1.1-1.fc30.x86_64 : Configures authentication and

No `-version` flag. You can check your installed package version with `rpm -q authselect`.

> ok, so to begin with, it kept complaining about `/etc/nssswitch.conf` not being generated by authselect, but it's rather sure, that noone ever touch that file. I found some bugreports about that, so I proceed with:

Perhaps, do you you `nss-mdns`? This package keeps overwriting nsswitch.conf generated by authselect and unfortunately, [it still has not been fixed](https://bugzilla.redhat.com/show_bug.cgi?id=1577243).

> ```
> authselect select sssd --force
> authselect enable-feature with-silent-lastlog
> authselect enable-feature with-pam-u2f
> ```
> 
> for some reason this produced twice `nemo` application to crash (while it wasn't running), and one system-core crash. So question 1: why is that possible to happen? Aren't we just modifying pam.d files?

Internally, besides writing pam and nsswitch, it also calls `dconf update` to update few dconf values. By any chance, do you have any coredumps or backtraces? Is this always reproducible? I'm also running cinnamon and have no issues.

> question 2: so now I have sssd profile as `current`. Where is this sssd profile has it's files, so that I can check them? I can see some files in `/etc/authselect` but there is no profile information...

Files under `/etc/authselect` are the generated configuration that is being used by the system. 
Profile definitions can be found at `/usr/share/authselect`.

> question 3: lets say, that I checked those files from question 2, and for now lets work with file `/etc/authselect/system-auth`. Configuration there for pam_u2f is:
> 
> ```
> auth        sufficient                                   pam_u2f.so cue
> ```
> 
> which happens to be what I'd like. But lets say, that I want to customize it (there's log of options for this pam) and some login managers (according to what I read) might have problems with option `cue`. So lets say I'd like to edit this for this `sssd` profile, not to use option `cue`. Where is the proper place to do such modification, how to say, that "with-pam-u2f" will not produce `cue` option?

If you need to modify the configuration, [please create a custom profile](https://github.com/pbrezina/authselect/wiki/How-To:-Create-new-profile).
 
> question 4: so in attempt to find the source files, I created new profile like `authselect show howDoesThisWork`, but sadly to find custom profiles in special location.

Why sadly?

> OK, but all these generated files are completely empty (np with that), which makes authselect commands to fail (not actually that ok).

Why not OK?

> Alright, so is there somewhere some documentation, how to correctly setup these files from authselect perspective (I know pam.d specifics).

`man authselect-profiles`. For your use case, try running `authselect create-profile my-profile -b sssd --symlink-meta --symlink-dconf --symlink-nsswitch` and just update pam configuration to your needs.

> And last step: to remove this custom profile `howDoesThisWork` is it ok to just delete it (as there is no command for that) or should we do something special?

Yes, to remove the profile just delete the directory. Perhaps a delete command is a good idea, since there is a create command. Please, file an RFE if you would like such command.

I hope this answers your questions.

**Comment by pbrezina** [comment] 2020-01-17 11:41
I'm going to close this issue. Feel free to reopen it if you have further

**Closed by pbrezina** 2020-01-17 11:41 UTC
Labels: question
