### ISSUE TITLE
`authselect create-profile --base-on=nis` creates empty file `smartcard-auth`

### ISSUE THREAD

**Issue by imsedgar** [pbrezina/authselect#83] opened 2018-09-07 16:56 UTC
Profile nis doesn't contain file `smartcard-auth`.
But if I run
`authselect create-profile --base-on=nis --symlink-meta --symlink-dconf --symlink=fingerprint-auth --symlink=postlogin nistest`
then it creates an empty file `/etc/authselect/custom/nistest/smartcard-auth` .

If I run
`authselect create-profile --base-on=nis --symlink-meta --symlink-dconf --symlink=fingerprint-auth --symlink=smartcard-auth --symlink=postlogin nistest`
then it creates a symbolic link `/etc/authselect/custom/nistest/smartcard-auth -> /usr/share/authselect/default/nis/smartcard-auth` which points to a nonexistent file.

Is this behavior intended?

**Comment by pbrezina** [comment] 2018-09-10 11:37
Creating the symbolic link is actually intended. If the base profile gets an update that contains the missing file, the custom profile will then automatically pick it up. If the link points to nowhere it is treated as empty file.

Empty file should not be created in my opinion so I would consider it a bug. It does not affect the functionality though.

Thank you for reporting the issue.

**Comment by pbrezina** [comment] 2018-09-24 12:19
I thought about it more and creating an empty file kind of depends on the point of view. If authselect finds out that a file is missing it creates a file with empty content. This is needed because PAM includes all the files so it needs to exist\* and it makes more clear that the file should be empty and it is not an oversight.

I think it is better to create an empty file with `create-profile` command even if it does not exist in the original profile. It makes more clear for an administrator that he/she can extend even files that are missing in the original profile.

I tent to close this issue as not a bug. But if you feel otherwise and insist on this functionality we can add some `--no-empty-files` switch there. Please, fell free to reopen if you want to.

\* I actually did not test how PAM behaves when the files that is included is missing, but either way seems more correct to create an empty file

**Closed by pbrezina** 2018-09-24 12:19 UTC
Labels: not a bug
